//! Human-readable markdown report generation for analysis results and
//! benchmark runs.

use crate::models::RepositoryAnalysis;

/// A single benchmark row, rendered by [`render_benchmark_report`].
#[derive(Debug, Clone)]
pub struct BenchmarkRow {
    /// Human readable name of the benchmark case.
    pub name: String,
    /// Number of files in the case.
    pub files: usize,
    /// Mean duration in milliseconds.
    pub duration_ms: f64,
    /// Throughput in files per second.
    pub files_per_second: f64,
    /// Optional heap-allocated bytes estimate.
    pub allocated_bytes: Option<u64>,
}

/// Render a full markdown report of an analysis result.
pub fn render_report(analysis: &RepositoryAnalysis) -> String {
    let mut out = String::new();
    out.push_str("# Repository Intelligence Report\n\n");
    out.push_str(&format!(
        "Analysed `{}` with `repository_intelligence` **{}**.\n\n",
        analysis.root, analysis.analyzer_version
    ));

    out.push_str("## Summary\n\n");
    out.push_str("| Metric | Value |\n|---|---|\n");
    out.push_str(&format!("| Files | {} |\n", analysis.summary.files));
    out.push_str(&format!(
        "| Directories | {} |\n",
        analysis.summary.directories
    ));
    out.push_str(&format!(
        "| Project roots | {} |\n",
        analysis.summary.project_roots
    ));
    out.push_str(&format!("| Bytes | {} |\n", analysis.summary.bytes));
    out.push_str(&format!(
        "| Scan duration | {:.2} ms |\n",
        analysis.performance.scan_duration_ms
    ));
    out.push_str(&format!(
        "| Analysis duration | {:.2} ms |\n",
        analysis.performance.analysis_duration_ms
    ));
    out.push_str(&format!(
        "| Throughput | {:.0} files/s |\n",
        analysis.performance.files_per_second
    ));
    out.push('\n');

    if !analysis.languages.is_empty() {
        out.push_str("## Languages\n\n");
        out.push_str("| Language | Files |\n|---|---|\n");
        for (language, count) in &analysis.languages {
            out.push_str(&format!("| {} | {} |\n", language.as_str(), count));
        }
        out.push('\n');
    }

    if !analysis.frameworks.is_empty() {
        out.push_str("## Frameworks\n\n");
        for framework in &analysis.frameworks {
            out.push_str(&format!("* {}\n", framework.display_name()));
        }
        out.push('\n');
    }

    let meta = &analysis.metadata;
    out.push_str("## Metadata\n\n");
    if !meta.package_managers.is_empty() {
        out.push_str(&format!(
            "* Package managers: {}\n",
            meta.package_managers.join(", ")
        ));
    }
    if !meta.build_systems.is_empty() {
        out.push_str(&format!(
            "* Build systems: {}\n",
            meta.build_systems.join(", ")
        ));
    }
    if meta.has_docker {
        out.push_str("* Containerised: yes\n");
    }
    if !meta.ci.is_empty() {
        out.push_str(&format!("* CI: {}\n", meta.ci.join(", ")));
    }
    if !meta.lockfiles.is_empty() {
        out.push_str(&format!("* Lockfiles: {}\n", meta.lockfiles.join(", ")));
    }
    out.push('\n');

    if !analysis.project_roots.is_empty() {
        out.push_str("## Project roots\n\n");
        for root in &analysis.project_roots {
            out.push_str(&format!("* {}\n", root));
        }
        out.push('\n');
    }

    if !analysis.entry_points.is_empty() {
        out.push_str("## Entry points\n\n");
        out.push_str("| File | Confidence | Heuristic |\n|---|---|---|\n");
        for entry in &analysis.entry_points {
            out.push_str(&format!(
                "| {} | {:.2} | {} |\n",
                entry.path, entry.confidence, entry.heuristic
            ));
        }
        out.push('\n');
    }

    if !analysis.modules.is_empty() {
        out.push_str("## Modules\n\n");
        for module in &analysis.modules {
            out.push_str(&format!(
                "* **{}** (`{}`, {}) — {} file(s)\n",
                module.name,
                module.root,
                kind_name(module.kind),
                module.files.len()
            ));
        }
        out.push('\n');
    }

    if !analysis.relationships.is_empty() {
        out.push_str("## Relationships\n\n");
        out.push_str("| Source | Target | Kind | Resolved |\n|---|---|---|---|\n");
        for rel in &analysis.relationships {
            out.push_str(&format!(
                "| {} | {} | {:?} | {} |\n",
                rel.source,
                rel.target,
                rel.kind,
                if rel.resolved { "yes" } else { "no" }
            ));
        }
        out.push('\n');
    }

    out.push_str("_Generated by `repository_intelligence`._\n");
    out
}

fn kind_name(kind: crate::models::ModuleKind) -> &'static str {
    match kind {
        crate::models::ModuleKind::Feature => "feature",
        crate::models::ModuleKind::Layer => "layer",
        crate::models::ModuleKind::Package => "package",
    }
}

/// Render a markdown benchmark summary table.
pub fn render_benchmark_report(rows: &[BenchmarkRow]) -> String {
    let mut out = String::new();
    out.push_str("## Benchmark results\n\n");
    out.push_str(
        "| Case | Files | Duration (ms) | Files/s | Allocated bytes |\n|---|---|---|---|---|\n",
    );
    for row in rows {
        let alloc = row
            .allocated_bytes
            .map(|b| b.to_string())
            .unwrap_or_else(|| "—".to_string());
        out.push_str(&format!(
            "| {} | {} | {:.2} | {:.0} | {} |\n",
            row.name, row.files, row.duration_ms, row.files_per_second, alloc
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analyzer::Analyzer;
    use crate::output::json::to_json;
    use tempfile::tempdir;

    #[test]
    fn renders_markdown_report() {
        let dir = tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("src")).unwrap();
        std::fs::write(dir.path().join("src/main.rs"), "fn main() {}").unwrap();
        std::fs::write(dir.path().join("Cargo.toml"), "[package]\nname=\"x\"").unwrap();
        let analysis = Analyzer::with_defaults().analyze(dir.path()).unwrap();
        let report = render_report(&analysis);
        assert!(report.contains("# Repository Intelligence Report"));
        assert!(report.contains("## Languages"));
        assert!(report.contains("## Entry points"));
        // JSON still valid.
        let _ = to_json(&analysis).unwrap();
    }

    #[test]
    fn renders_benchmark_table() {
        let rows = vec![BenchmarkRow {
            name: "small".into(),
            files: 100,
            duration_ms: 5.0,
            files_per_second: 20_000.0,
            allocated_bytes: Some(1024),
        }];
        let report = render_benchmark_report(&rows);
        assert!(report.contains("small"));
        assert!(report.contains("20000"));
    }
}
